# File: .github/workflows/repo-sync.yml

on:
  schedule:
    - cron: '5 6 * * *'
  workflow_dispatch:
  watch:
    types: started

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:  
      - name: IP
        run: sudo ifconfig -a
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/RayWangQvQ/BiliBiliTool.git"
          source_branch: "*"
          destination_branch: "*"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
